FROM nginx:latest

COPY about.html /usr/share/nginx/html/about.html
COPY contact.html /usr/share/nginx/html/contact.html
COPY frog.html /usr/share/nginx/html/frog.html
COPY index.html /usr/share/nginx/html/index.html